### ISSUE TITLE
Too Many Incoming Requests

### ISSUE THREAD

**Issue by samuelya** [rebus-org/Rebus.AzureServiceBus#10]
I am using standard azure bus as transport layer. I found each of my services generates almost 4.5 millions requests every month even if it is not used!!!!. So, is it normal behaviour?! Also, Is any way to reduce requests count as Microsoft charges per requests/operations. 

Thanks

**Comment by mookid8000** [comment]
Yes it is normal behavior.

If you want to reduce the number of requests, you can

- reduce the parallelism via `.Options(o => o.SetMaxParallelism(...))`
- configure [back-off times](https://github.com/rebus-org/Rebus/wiki/Back-off-strategy)
