### ISSUE TITLE
Create an extensibility point to name topics

### ISSUE THREAD

**Issue by heberop** [rebus-org/Rebus.AzureServiceBus#11]
Creating an extensibility point to name topics is useful if you want to use another name convention, changing the default topic name based on type to bounded context.

For example, I would like to change the topic name from this:
![image](https://user-images.githubusercontent.com/6517462/39203579-8ea1191e-47cb-11e8-9364-ec6223e44fa0.png)

to this:
![image](https://user-images.githubusercontent.com/6517462/39203592-99d104fc-47cb-11e8-8a8a-077c290440ae.png)

I think we can create an extension method in `AzureServiceBusTransportSettings` to define the convention to name topics, like this:

```cs
internal Func<string, string> TopicNamingConvention { get; set; }
    = topic => topic.ToValidAzureServiceBusEntityName();

public AzureServiceBusTransportSettings EnableTopicNamingConvention(Func<string, string> convention)
{
    TopicNamingConvention = convention;

    return this;
}
```

Then, when we are configuring the endpoint:

```cs
services.AddRebus(configure => configure
                    .Logging(l => l.ColoredConsole())
                    .Transport(t => 
                        t.UseAzureServiceBus(connectionString, endpoint)
                            .EnablePrefetching(100)
                            .EnableTopicNamingConvention(topic => topic.MyConvention()))
```

Another way is to create an interface like `INamingConvention` and implementing that.

**Comment by mookid8000** [comment]
I can definitely see how this would be useful, but I am not sure the Azure Service Bus transport would be the best place to add this extensibility point.

I am thinking that it might be a nice feature in general to be able to affect how Rebus maps types to topics. You can see how subscribe is implemented here: https://github.com/rebus-org/Rebus/blob/master/Rebus/Bus/RebusBus.cs#L198 - as you can see, it simply calls the [`GetSimpleAssemblyQualifiedName`](https://github.com/rebus-org/Rebus/blob/master/Rebus/Extensions/TypeExtensions.cs#L34-L38) extension.

My initial idea would be extend the `IRouter` service with the ability to perform this mapping, and thus with the ability to be overridden...

What's your thoughts about this?

**Comment by heberop** [comment]
I agree with you that the `IRouter` interface is the natural place to put this functionality.

Do you have a suggestion of name for this method on IRouter interface? Or can I use TopicNameConvention?

**Comment by mookid8000** [comment]
> I was reading the code and I think we can't modify IRouter because we can broke some custom implementation of IRouter.

You are absolutely right about that 🙂 also, when thinking some more about it it's not really "routing", it's more about what happens _right before_ routing, if you know what I mean?

> PS: I think we need to move these thread to Rebus repo ;)

BAM! 👉 👉 👉  https://github.com/rebus-org/Rebus/issues/692
