### ISSUE TITLE
Using Shared access signature is not working

### ISSUE THREAD

**Issue by runes83** [rebus-org/Rebus.AzureServiceBus#14]
I get this error when trying to use a Azure servicebus Shared access key connection string

ArgumentException: ConnectionString used to create NamespaceManager shouldn't include EntityPath as NamespaceManager is at Namespace level.

**Comment by runes83** [comment]
We use this DoNotCreateQueues() extension on UseAzureServiceBus that works today but the UseAzureServiceBusAsOneWayClient does not return settings to the extension does not work.

**Comment by mookid8000** [comment]
Rebus.AzureServiceBus 5.0.1 has now been released with a fix that allows for using connection strings with an EntityPath in it.

As you correctly mentioned, the fix was to _remove_ the EntityPath element when using the connection string.

**Comment by mookid8000** [comment]
Rebus.AzureServiceBus 6.0.1 has had the fix applied too
