### ISSUE TITLE
Published release version depends on pre-release version

### ISSUE THREAD

**Issue by vladimir-kovalyuk** [rebus-org/Rebus.AzureServiceBus#16]
https://github.com/rebus-org/Rebus.AzureServiceBus/blob/e6d6fa7d57fe030d3ec6d58b28e8887b76e862ce/Rebus.AzureServiceBus/Rebus.AzureServiceBus.csproj#L51

**Comment by mookid8000** [comment]
wow that's weird! – I didn't think that was even possible with NuGet

**Comment by Meyce** [comment]
Is it safe to use Rebus.AzureServiceBus 6.0.2 or should we wait for an update version without the beta reference?

**Comment by mookid8000** [comment]
oh it's safe enough... but it looks pretty silly, so I've released Rebus 5.0.0 now 😄 🎉 😈 🤘 

Rebus.AzureServiceBus 6.0.3 (with a proper dependency on Rebus 5.0.0) is out now too!

Thanks for bringing this up 😁
