### ISSUE TITLE
Using path in connection string no longer works

### ISSUE THREAD

**Issue by vegar** [rebus-org/Rebus.AzureServiceBus#17]
We have some services using v3 of rebus. Now we have a new .net core based service using v6.

When sharing a single service us between multiple developers in test environment, we have included the machine name in the connection string for namespacing. e.g. `Endpoint=sb://sharedbus.servicebus.windows.net/mymachine;SharedAccessKeyName=....`

In the .net core world, this doesn't work. The `path`-part of the endpoint is ignores.

I'm not sure if it is because of the new `Rebus.AzureServiceBus`-implementation, or if it is the new  [azure-service-bus-dotnet](https://github.com/Azure/azure-service-bus-dotnet), and I have to admit that I don't know rebus nor service bus good enough to know where to start digging...

My rebus setup is simple:

```
            var bus = Configure
                .With(_activator)
                .Logging(x => x.Serilog())
                .Transport(t => t.UseAzureServiceBus("Endpoint=sb://...servicebus.windows.net/mymachine;...., "MyInput"))
                .Options(o =>
                {
                    o.SimpleRetryStrategy(_rebusOptions.ErrorQueue);
                })
                .Start();

            await bus.Subscribe<MyEventMessage>();
```

I would expect a `mymachine/myinput`-queue, and a `mymachine/myeventmessage`-topic with one subscription. Instead I get `myinput`-queue and `myeventmessage`-topic. 

Any idea what changed?
Is there a different way of achieving my desired result?

**Comment by vegar** [comment]
> Is there a different way of achieving my desired result? 

Decorating the ISubscriptionStorage seems like a good fit.
The queue names are easy to prefix anyway.

**Comment by mookid8000** [comment]
I've investigated this now – Rebus' Azure Service Bus transport is passing the connection string directly to `ManagementClient`, which it then uses to create its queues.

It seems the management client might deviate slightly from how the old driver worked.

If you want queue names with slashes in them, you can simply put it in the queue name, so I suggest you simply prefix your queue names.

**Comment by mookid8000** [comment]
Ah, now I understand why you suddenly brought the subscription storage into the talk 😁 pretty clever solution!

**Comment by vegar** [comment]
I won’t take credit for neither the existence of a ISubscriptionStorage nor the convenient Decorate method that I found ;-)
