### ISSUE TITLE
Add Transport configuration options to support MS guidance for high message throughput

### ISSUE THREAD

**Issue by trevorreeves** [rebus-org/Rebus.AzureServiceBus#2]
[This Azure Service Bus article](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-performance-improvements) provides a nice overview of how to achieve a high message throughput.  Towards the bottom of the article it has a nice summary of the steps to be taken to meet different use cases:

1. Maximize the throughput of a single queue. The number of senders and receivers is small.

2. Maximize overall throughput of multiple queues. The throughput of an individual queue is moderate or high.

3. Minimize end-to-end latency of a queue or topic. The number of senders and receivers is small. The throughput of the queue is small or moderate.

etc..

I can see some changes required in the Rebus transport in order to support the recommendations described in the article.  Additionally, I see the need for the ability for consumers to be able to vary these settings per Queue as different queues can be used for different use cases inside the same application (or would you have the opinion that an application should setup multiple IBus instances to achieve this instead?).

- The ability to specify a configurable number of message factories to create senders for specific Queues.

- The ability to specify a configurable number of message factories to create receivers for specific Queues.

- The ability to configure batch flushing in the client, and specify the 'BatchFlushInterval' for specific Queues (that's via MessageFactory->MessageFactorySettings-> NetMessagingTransportSettings).

- The ability to set the prefetch count per Queue.

**Comment by mookid8000** [comment]
>The ability to specify a configurable number of message factories to create senders for specific Queues.

Rebus caches and reuses topic clients and queue clients. Moreover, all outgoing messages are stored in-mem and sent at once after the Rebus handler has been executed, using the batch API when possible.

>The ability to specify a configurable number of message factories to create receivers for specific Queues.

Each `IBus` uses a single `QueueClient` for its input queue. I have achieved receive rates of over 2000 msg/s by setting Rebus' parallelism high enough. Do you think it would be possibly to go beyond that by using multiple `QueueClient` instances?

>The ability to configure batch flushing in the client, and specify the 'BatchFlushInterval' for specific Queues (that's via MessageFactory->MessageFactorySettings-> NetMessagingTransportSettings).

This would not play well with Rebus' at-least-once delivery guarantee – all outgoing messages must be sent before the message being handled is acknowledged, otherwise you run the risk of crashing hard and losing messages that should have been sent.

>The ability to set the prefetch count per Queue.

Funnily enough I once removed Rebus' own prefetching and replaced it by setting the `PrefetchCount` property on the input queue, but it didn't seem to improve the receive rate. I might have done something wrong, though. Do you have any experience with this?

**Comment by trevorreeves** [comment]
#### The ability to specify a configurable number of message factories to create senders for specific Queues.

 >Rebus caches and reuses topic clients and queue clients. Moreover, all outgoing messages are stored in-mem and sent at once after the Rebus handler has been executed, using the batch API when possible.

Microsoft's guidance is that because each QueueClient instance, well in fact each QueueClient instance created from the same MessageFactory instance, performs communication over the same TCP connection, so the throughput will be implicitly limited by the capacity of that single TCP connection.  To avoid this restriction, create QueueClients from multiple MessageFactorys.  

In Rebus' case, that could be to allow configuration of the number of MessageFactorys per Queue/Topic name, so each Queue/Topic has a collection of clients and a simple round-robin approach to choose which client to use when sending.  The default value of course can be 1 to match the current behavior.

I have approximated this behavior in my load tests by using multiple buses, and have seen a significant increase in throughput (going from 1 to 3 increases throughput by 2.5 times).  I am just putting together an initial implementation inside the Azure Transport to see if the same gains can be achieved with a simple round-robin approach across a collection of clients.

#### The ability to specify a configurable number of message factories to create receivers for specific Queues.
>Each IBus uses a single QueueClient for its input queue. I have achieved receive rates of over 2000 msg/s by setting Rebus' parallelism high enough. Do you think it would be possibly to go beyond that by using multiple QueueClient instances?

I think for the same reason as the Sends mentioned above, MS are recommending a similar approach for receiving.  I haven't focused on this yet in my load tests, but I can now send ~8000 msg/s (on standard tier) using multiple (3) clients, at which point my consumers are falling behind significantly.

#### The ability to configure batch flushing in the client, and specify the 'BatchFlushInterval' for specific Queues (that's via MessageFactory->MessageFactorySettings-> NetMessagingTransportSettings).
>This would not play well with Rebus' at-least-once delivery guarantee – all outgoing messages must be sent before the message being handled is acknowledged, otherwise you run the risk of crashing hard and losing messages that should have been sent.

OK, yes of course.  

My load testing so far (for SqlServer and Azure Service Bus) - for small number of producers & consumers with high throughput) is showing the sends are the bottleneck (especially on SqlServer), so I need to look at ways to improve this situation.

So this points towards implementing batch sending from the Rebus API level - then the delivery guarantees become transparent to the producers, i.e. the responsibility is with the producers to create a batch of messages with a guarantee level they are comfortable with.

I am aware this is another topic of conversation & Rebus had batch sending in the past ...

Just for info, I have implement an approximation of batch sending at the transport level for SqlServer.  SqlServer starts to struggle with batch sizes above 4, but until then, I get increases in through put as a function of batch size.

I plan to do the same for Azure tomorrow.

#### The ability to set the prefetch count per Queue.
>Funnily enough I once removed Rebus' own prefetching and replaced it by setting the PrefetchCount property on the input queue, but it didn't seem to improve the receive rate. I might have done something wrong, though. Do you have any experience with this?

I was more raising the question that would it be useful generally to allow a per Queue/Topic configuration option for this, when an application is using multiple Queues for different scenarios?  I don't know yet if this will be a requirement of my consumers, but it could be.

**Comment by mookid8000** [comment]
Let's close this one until new updated guidance from Microsoft is available targeting [the new driver](https://github.com/Azure/azure-service-bus-dotnet)
