### ISSUE TITLE
Update referenced version of Microsoft.Azure.AzureServiceBus

### ISSUE THREAD

**Issue by Meyce** [rebus-org/Rebus.AzureServiceBus#24]
The referenced version of Microsoft.Azure.AzureServiceBus(3.1.0) has a reference constraint on Microsoft's ADAL library of less than 4.0.0.  Can the version that is referenced be updated to the latest(3.2.1) which supports 4.x versions of the ADAL library?  We use the ADAL library in other places in our code which is currently at 4.4.2.  The constraint via the 3.1.0 library which Rebus.AzureServiceBus uses causes warnings through our code.

I can fork/create a PR for this to move it along if that works.

**Comment by mookid8000** [comment]
Fixed and released as Rebus.AzureServiceBus 6.0.6 and 7.0.0-a06

Thanks for bringing this up 👍
