### ISSUE TITLE
OperationTimeout is not parsed from connectionstring by the new Microsoft.Azure.ServiceBus

### ISSUE THREAD

**Issue by jr01** [rebus-org/Rebus.AzureServiceBus#33]
The old Azure servicebus lib parsed the OperationTimeout from the connectionstring, the new lib doesn't seem to do that. 

https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L101

https://github.com/Azure/azure-service-bus-dotnet/blob/master/src/Microsoft.Azure.ServiceBus/ServiceBusConnection.cs

https://github.com/Azure/azure-service-bus-dotnet/blob/master/src/Microsoft.Azure.ServiceBus/ServiceBusConnectionStringBuilder.cs

Suggestion: add a Rebus transport setting to set the ReceiveTimeout.

**Comment by mookid8000** [comment]
Good idea 😄
