### ISSUE TITLE
Error header exceeding 65K

### ISSUE THREAD

**Issue by jr01** [rebus-org/Rebus.AzureServiceBus#35]
A bug in a message handler resulted in a rather large stacktrace. After the default number of Rebus retries got this error:

> An error occurred when attempting to complete the transaction contextRebus.Exceptions.RebusApplicationException: Could not send to queue 'error' --->
> Microsoft.Azure.ServiceBus.MessageSizeExceededException: A serialization error occurred while processing the message header stream with sequence number 207001985.
> The serialization process return the following message: The size quota for this stream (65536) has been exceeded.. (...)
>    at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__52.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__39.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass32_0.<<GetOutgoingMessages>b__3>d.MoveNext()
>    --- End of inner exception stack trace ---
>    at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass32_0.<<GetOutgoingMessages>b__3>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Rebus.AzureServiceBus.AzureServiceBusTransport.<>c__DisplayClass32_1.<<GetOutgoingMessages>b__1>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Rebus.Transport.TransactionContext.<Invoke>d__24.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Rebus.Transport.TransactionContext.<RaiseCommitted>d__21.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Rebus.Transport.TransactionContext.<Complete>d__19.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
>    at Rebus.Workers.ThreadPoolBased.ThreadPoolWorker.<ProcessMessage>d__19.MoveNext()

This is with Rebus.AzureServicebus 7.0.0-a12 and Rebus 5.2.1. 

I'm not sure (yet) if this would also have occurred with older Rebus/Rebus.AzureServicebus versions, at least I haven't run into this in the past few years.

**Comment by jr01** [comment]
Repro:

```
[TestFixture]
    public class VerifyErrorHeaderSize : FixtureBase
    {
        [Test]
        public async Task ItWorks()
        {
            var name = TestConfig.GetName("namespace");
            var queueName = $"{name}/test-queue";
            Using(new QueueDeleter(queueName));

            var activator = new BuiltinHandlerActivator();

            Using(activator);

            var done = new ManualResetEvent(false);
            int tryCount = 0;
            const int MaxDeliveryAttempts = 3;

            activator.Handle<string>(message => {
                tryCount++;
                if (tryCount == MaxDeliveryAttempts)
                {
                    done.Set();
                }

                var exceptionMessage = new string('a', 30*1024); // 30 KB * 3 < 256KB max message size.
                throw new InvalidOperationException(exceptionMessage);
            });

            Configure.With(activator)
                .Transport(t => t.UseAzureServiceBus(AsbTestConfig.ConnectionString, queueName))
                .Options(o => o.SimpleRetryStrategy(maxDeliveryAttempts: MaxDeliveryAttempts))
                .Start();
            
            await activator.Bus.SendLocal("Hello World");

            done.WaitOrDie(TimeSpan.FromSeconds(10),
                errorMessage: "Message did not finish handling within timeout");

            // Wait for Rebus to move the message to the error queue.
            await Task.Delay(5000);

            // Check ?? how ??  See test output for now ....
        }
    }
```

**Comment by jr01** [comment]
Also when changing to new string('a', **66***1024); the total message size exceeds the max 256KB allowed on ASB resulting in:

> Could not send to queue 'error' ---> Microsoft.Azure.ServiceBus.MessageSizeExceededException: The received message (delivery-id:0, size:283814 bytes) exceeds the limit (262144 bytes) currently allowed on the link.

**Comment by mookid8000** [comment]
Hmm-... I seem to recall having made something some time that would limit the size of the headers somehow... with ASB, I think the 256 kB limit is the total message size, so that's the payload including  the headers.... but there's also a limit that applies to the headers, which IIRC limits each value to 32768 chars... I'll have time to look at it tonigh

**Comment by mookid8000** [comment]
Rebus.AzureServiceBus 7.0.0-a13 will now truncate the error details header, if its length gets above 32k characters.

The number of characters is picked as an arbitrary number that feels quite safe, because I don't think it's possible to precisely estimate how much space the headers are going to take up.
