### ISSUE TITLE
The "renewal peek lock" task stops before actually terminating the handler, causing another thread to process the message again in another thread and "invalid lock toke / message already removed" errors in the original one.

### ISSUE THREAD

**Issue by Rzpeg** [rebus-org/Rebus.AzureServiceBus#42]
Hey,

I've noticed that sometimes, with the renewal peek lock enabled, the same message is consumed and processed by multiple threads in parallel, when specific conditions are met. 

I've debugged the Rebus Azure Transport and I believe I've found the reason for this behavior.

Imagine the following:
- The ASB lock time is 60 seconds
- Transport Renewal is enabled.
- The handler objective is to generate 1.000 new messages to "bus.Send".
- It takes 59 seconds to run the handler code.

What happens in this scenario is that because of the transaction, both effective message dispatch and stopping of renewal task are callbacks executed on transaction commit:

1. Renewal callback (https://github.com/rebus-org/Rebus.AzureServiceBus/blob/921a3048514b946d2df818dc4d874354ac0b1f7d/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L559)

2. Dispatch callback (https://github.com/rebus-org/Rebus.AzureServiceBus/blob/921a3048514b946d2df818dc4d874354ac0b1f7d/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs#L473)

The problem is that, when executing the commit callbacks in TransactionContext, the renewal process is killed **before** dispatching the messages, thus, making it possible for rebus to re-consume the same message in another thread, while the original one is still dispatching the stored messages. When the original thread is done processing and calls for ASB CompleteAsync (or AbandonAsync for that matter) with the lock token, the infamous error is thrown, because the token is, indeed, invalid - the message is being consumed by another thread and now has a different token.

This creates an infinite cycle generating messages and errors ad infinitum. 

The lock renewal process should be the last one to get killed with a small delay after disposing the message, to guarantee the correct onCommit process.

Regards,
Stan

**Comment by mookid8000** [comment]
Should be fixed by #46
