### ISSUE TITLE
EnsureTopicExists  and GetOrCreateSubscription  implementation could be improved

### ISSUE THREAD

**Issue by sabbadino** [rebus-org/Rebus.AzureServiceBus#44]
Hi , I had a look at the implementation of EnsureTopicExists : I suggest to use TopicExistsAsync.
This would avoid to generate many exceptions (which clutter my application insights logs :) btw).

Same goes for the implementation of method GetOrCreateSubscription : you could use SubscriptionExistsAsync

InnerCreateQueue is fine : it uses QueueExistsAsync

Thank you 
enrico 

https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.servicebus.management.managementclient.topicexistsasync?view=azure-dotnet#Microsoft_Azure_ServiceBus_Management_ManagementClient_TopicExistsAsync_System_String_System_Threading_CancellationToken_

**Comment by mookid8000** [comment]
Fixed in the more recent versions – Rebus.AzureServiceBus 7.0.0-a19 is on NuGet.org now 🙂
