### ISSUE TITLE
All exception from renewing peek locks are being swallowed and not logged

### ISSUE THREAD

**Issue by macchmie3** [rebus-org/Rebus.AzureServiceBus#54]
The method in `MessageLockRenewer.Renew `  is swallowing all exceptions:

```
public async Task Renew()
{
	try
	{
		await _messageReceiver.RenewLockAsync(_message);

		SetNextRenewal();
	}
	catch { } //< will automatically be retried if it fails

}
```

Because of that the is no way exceptions would be logged in `AzureServiceBusTransport.RenewPeekLocks`:

```
try
{
	await r.Renew().ConfigureAwait(false);
	
	_log.Debug("Successfully renewed peek lock for message with ID {messageId}", r.MessageId);
}
catch (Exception exception)
{
	_log.Warn(exception, "Error when renewing peek lock for message with ID {messageId}", r.MessageId);
}
```

**Comment by mookid8000** [comment]
True.... I wonder, what would a good strategy be when the renewal fails?

Should it be retried a couple of times? And if so, how many times and for how long?

**Comment by macchmie3** [comment]
It may be good to take into consideration type of exceptions - if it was a timeout i think it is already a good backoff.  You can easily implement backoffs by "playing" with Set Next Renewal. Maybe if you were to do a retry you can go for like 10% of remaining lock time instead of 50%? There are just some loose ideas.

**Comment by mookid8000** [comment]
Hmm this issue has been around for a while, and the basic problem with swallowed exceptions has not been a problem for a long time, as peek lock renewal exceptions are logged with the WARN level as they should.

There's no real retry strategy though, as peek locks that fail to renew will be automatically retried after 10 s in the next renewal round.

As I am not sure that it makes sense to come up with anything more sophisticated than this, I am closing the issue now.
