### ISSUE TITLE
Azure service bus session support

### ISSUE THREAD

**Issue by sabbadino** [rebus-org/Rebus.AzureServiceBus#59]
Hi, is it possible to use asb sessions in rebus asb transport ? 
Thank you.
Enrico

**Comment by mookid8000** [comment]
Unfortunately, no.

What would you like to use them for?

**Comment by sabbadino** [comment]
For scenarios where fifo processing is required .. as described here 
https://docs.microsoft.com/en-us/azure/service-bus-messaging/message-sessions

**Comment by mookid8000** [comment]
OK, I guess it _could_ be supported by enabling it somehow, and then the bus would manage the session underneath the covers, ensuring that received messages are processed in order (although they would belong to different sessions).

But what if there's an error, and the current message is moved to the dead-letter queue?

The way Rebus does it, simply by using another queue (or by storing the message in Fleet Manager, if you're using Rebus Pro), the message would be "removed" from the session, and the next message would be received.... do you have any good ideas on how one would handle this situation?

**Comment by mccow002** [comment]
Has there been any progress on this? I have a scenario where I need messages processed synchronously, and sessions gives me that. But I have built a lot of code around rebus, so I really don't want to pull it out.

**Comment by mookid8000** [comment]
I think the question

> But what if there's an error, and the current message is moved to the dead-letter queue?
> 
> The way Rebus does it, simply by using another queue (or by storing the message in Fleet Manager, if you're using Rebus Pro), the message would be "removed" from the session, and the next message would be received.... do you have any good ideas on how one would handle this situation?

needs to be given some thought to make any progress on this ... do you have experience with Azure Service Bus' session support? How does it work together with ASB's built-in deadlettering?

**Comment by mccow002** [comment]
I have a little experience with it - Before I switched to Rebus, I was using QueueClient RegisterSessionHandler method, and from what I saw, it dead-letters messages when they fail the same as a non-session queue.

**Comment by mookid8000** [comment]
@mccow002 so, do other messages that belong to the same session then wait for the missing message to be re-queued? And if so, how does that happen?

**Comment by mccow002** [comment]
I threw together a linqpad file to test this. The test sends 5 messages in a session, then the receiver throws an exception on message 3.

It looks like it retries step 3 10 times, dead-letters it, then moves on to message 4. It doesn't look like it waits for a message to be completed successfully before moving on.

**Comment by mookid8000** [comment]
Hmmm.... honestly, I think you would be better off building your system with some degree of tolerance towards reordered messages.

If you could tell me more about which problems you are trying to solve, then maybe I would be able to point to some kind of alternative solution that would fit better into the way Rebus works.

**Comment by georgechond94** [comment]
Any idea if this could be supported in the future?
The main reason to support sessions, I see, is for FIFO scenarios. Amazon SQS supports FIFO out of the box, in Azure SB we have to use sessions for that.

**Comment by georgechond94** [comment]
This is pretty much what's needed -> https://github.com/rebus-org/Rebus.AmazonSQS/issues/24 but for `SessionId` instead of `MessageGroupId`. Is a PR welcome? 😄

**Comment by georgechond94** [comment]
https://github.com/rebus-org/Rebus.AzureServiceBus/pull/84 here it is. As the same feature is supported on `Rebus.AmazonSQS`, it seems logical to be included here as well.

Please let me know if you consider merging this or more thought/changes are required.

**Comment by mookid8000** [comment]
#84 adds support for Rebus+ASB sessions.

It should be noted that everyone who wants to use sessions should make themselves aware of their shortcomings, specifically in regard to reordered messages due to messages being dead-lettered (i.e. moved to the error queue, thus having been "correctly handled" in the POV of the ASB session, but being missing from the sequence from the POV of the consumer).

It's available on NuGet.org as Rebus.AzureServiceBus 9.1.0 now! 🙂

**Comment by sabbadino** [comment]
Hi, there are a couple of things not clear to me (i admit i have not gone through all the commits):
i see a setting  transport.RequiresSession : does it mean that rebus setup must be all yes or all no sessions ? cannot it be a per queue / topic setting ? (and i think that this can be queried from asb , no need for a setting .. and rebus must know if the queue /topic is session is enabled or not since you have to use 2 different apis) .. 

if i have session enabled topics , what about the queue asb use to convey the messages to the service ? will it be a session aware queue as well ? .. if not the goal of fifo, when many consumer dequeue, will be lost i suppose.

**Comment by sabbadino** [comment]
I understand first question does not makes sense somehow ..
Topics and queues are created by rebus .. and i see no easy way to do opt in  for session or not at the topic level since rebus abstract this concept (change the message type to topic mapping convention and different topics are created).
