### ISSUE TITLE
Net5 incompatibility

### ISSUE THREAD

**Issue by kvpt** [rebus-org/Rebus.AzureServiceBus#60]
Hi,

I try to migrate one of my project to Net5.0, I have for now to manually update two dependencies of this package for my project to works.

- Microsoft.Azure.Amqp need 2.4.6+ version which contain a fix for Net5.0 https://github.com/Azure/azure-amqp/commit/709eafdeae081734cc1f6962d981e3a0402e6695
- Microsoft.Azure.ServiceBus need 4.1.3+ version to permit System.IdentityModel.Tokens.Jwt to be greater than 5.X

I didn't make a PR because I don't know if you want to update to the minimal or the latest version of these packages.

**Comment by mookid8000** [comment]
I've pushed Rebus.AzureServiceBus 8.0.0-a1 where I've updated the driver to the newest version available. I hope that fixes your problem 🙂 let me know if it works for you, and then I'll release a proper version.

**Comment by kvpt** [comment]
Thank you !
Updated the library and removed the others dependencies and my tests passes so I confirm the new version fixed it for me 👍.

**Comment by mookid8000** [comment]
Proper version has now been pushed to NuGet.org 👉  Rebus.AzureServiceBus 8.0.0 🙂
