### ISSUE TITLE
Migration to Azure.Messaging.ServiceBus is on plan?

### ISSUE THREAD

**Issue by binick** [rebus-org/Rebus.AzureServiceBus#69]
A few months ago MSFT has release a [Azure.Messaging.ServiceBus](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/) to replace [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus).

Although [Microsoft.Azure.ServiceBus](https://www.nuget.org/packages/Microsoft.Azure.ServiceBus) isn't deprecated some features require certain tricks to works, like a [managed identities](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/overview), see also https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration.

At the moment I noticed only this inconsistency between the use of Rebus with other Azure packages, it is not excluded that there are others, but above all it is not excluded that in the future others doesn't will be added.

**Comment by mookid8000** [comment]
It's definitely the plan to do so 🙂
