### ISSUE TITLE
Unable to use HttpProxy with AmqpWebSockets transport 

### ISSUE THREAD

**Issue by sergii-kryzh** [rebus-org/Rebus.AzureServiceBus#74]
In my company in some on-prems/private-cloud environments we are forced to use HTTP proxy to whitelist outgoing connections. 

We are actively using Azure Service Bus and have an in-house solution which is based on older `Microsoft.Azure.ServiceBus` library.
In case of this in-house library it's pretty simple to enable HTTP proxy on Linux docker images running in K8S by:
1.  Setting `HTTPS_PROXY`, `HTTP_PROXY`, and `NO_PROXY` environment variables.
2. Appending a transport to connection string: `Endpoint=sb://ZZZ.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=YYY;TransportType=AmqpWebSockets`
3. We are using `mcr.microsoft.com/dotnet/runtime:3.1.18-alpine3.13` base image.

Meanwhile we are running a pilot of Rebus and have already built an application which uses Rebus with AzureServiceBus as transport and SQL Server for Sagas.
However when we deploy everything to one of those "special" environments and configure everything the way we used to do it for older apps it unfortunately does not work:
1. Seems like Rebus is built using `Azure.Messaging.ServiceBus`.
2. Now if we look here [https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/AzureServiceBusTransport.cs] and more specifically here:
`var connectionStringWithoutEntityPath = _connectionStringParser.GetConnectionStringWithoutEntityPath();`
`_client = new ServiceBusClient(connectionStringWithoutEntityPath, clientOptions);`
`_managementClient = new ServiceBusAdministrationClient(connectionStringWithoutEntityPath);`
3. Then it seems like HttpProxy must be set explicitly in `clientOptions.WebProxy` property
4. However current configuration API does allow to provide HttpProxy explicitly (example from our app):
`t.UseAzureServiceBus(azureServiceBusConnectionString, appOptions.Rebus?.InputQueueName ?? throw new Exception("Rebus input queue name is not configured.")).AutomaticallyRenewPeekLock();`

**Comment by mookid8000** [comment]
Ah, damn! But, if I understand you correctly, it would work if the `UseAzureServiceBus` method simply had an optional `IWebProxy` argument that it would pass to the client options, right?

**Comment by sergii-kryzh** [comment]
So queue/topic client should work. I'm not sure about management client.
I'm planning on branching this lib and building it into our private NuGet repo today/tomorrow.

I can then share a patch.
Is that OK?

**Comment by mookid8000** [comment]
Yes, that would be awesome 👍

**Comment by sergii-kryzh** [comment]
@mookid8000 , so I've finally figured out what was wrong.

Quick search on Internet reveals that originally Microsoft wanted to use `TransportType=AmqpWebSockets`.
For instance: [MS Docs for old lib](https://docs.microsoft.com/en-us/azure/service-bus-messaging/service-bus-amqp-dotnet)
`Endpoint=sb://[namespace].servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=[SAS key];TransportType=AmqpWebSockets.`

However Rebus library uses `Transport=AmqpWebSockets` instead.
Here is a code: [ConnectionStringParser.cs](https://github.com/rebus-org/Rebus.AzureServiceBus/blob/master/Rebus.AzureServiceBus/AzureServiceBus/ConnectionStringParser.cs)

So I'm not sure if this is intentional, but maybe it could be modified to something like this (should also be backwards compatible to current Rebus logic):
`public ServiceBusTransportType Transport => (ServiceBusTransportType)Enum.Parse(typeof(ServiceBusTransportType), _parts.GetValueOrNull("Transport") ?? (ServiceBusTransportType)Enum.Parse(typeof(ServiceBusTransportType), _parts.GetValueOrNull("TransportType") ?? nameof(ServiceBusTransportType.AmqpTcp));`

What do you think?

**Comment by mookid8000** [comment]
Looks like that would work just fine. 🙂

**Comment by konradzuse** [comment]
This just caught me out when updating to the latest version from v6. I was using "TransportType=AmqpWebSockets" previously.

**Comment by sergii-kryzh** [comment]
So I've eventually hacked it this way:
`Endpoint=sb://[namespace].servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=[SAS key];TransportType=AmqpWebSockets;Transport=AmqpWebSockets;`
Now in all cases cases `Rebus` + `Azure.Messaging.ServiceBus` and `Microsoft.Azure.ServiceBus` it works fine and does not complain.
