### ISSUE TITLE
Not receiving any messages

### ISSUE THREAD

**Issue by froens** [rebus-org/Rebus.AzureServiceBus#78]
Hi there,

I've tried to setup Rebus with ASB. I have 2 applications:

- ASP.NET - Responsible for listening for messages on topics
- Console App - Publishing messages on topics

### Asp.net application
Asp.net application is setup with the ServiceProvider-extension:

Excerpt from startup.cs
```csharp
services.AddRebus(
                configure => configure
                    .Transport(
                        t => t.UseAzureServiceBus("<Connection-String>", "AIH.Workflows-frederik"))
            );
```

To subscribe, I have a class which gets the IBus injected and I run Subscribe:
```csharp
    public class CreateSubscriptions : IStartupTask
    {
        private readonly IBus _bus;
        private readonly IEnumerable<Type> _messageTypes;

        public CreateSubscriptions(IBus bus, IEnumerable<Type> messageTypes)
        {
            _bus = bus;
            _messageTypes = messageTypes;
        }

        public int Order => 1000;

        public async Task ExecuteAsync(CancellationToken cancellationToken = default)
        {
            foreach (var msgType in _messageTypes)
            {
                await _bus.Subscribe(msgType);
            }
        }
    }
```

Subscribe is called with 2 types:
- FileCreated
- SuggestionCreated

### Console Application

```csharp
var someContainerAdapter = new BuiltinHandlerActivator();

            var bus = Configure.With(someContainerAdapter)
                               .Transport(t => t.UseAzureServiceBusAsOneWayClient("<Connection-String>"))
                               .Start();

            for(int i = 0; i < 3; i++)
            {
                await bus.Publish(new FileCreatedz
                {
                    Name = $"File {i}",
                    CreatedDate = DateTime.Now
                });
            }
```

### Symptoms
When I run the ASP.Net-application:
- On Azure Service Bus, I can see 2 topics created (one for each type).
- A subscription under each Topic called "AIH.Workflows-frederik" is created.
- A queue called "AIH.Workflows-frederik" is created, and the two subscriptions is set to forward messages to the queue

When I run the Console-Application:
- Messages end up in the queue but are not consumed.<br/>
<br/>
<br/>
<br/>
What am I doing wrong :-) ? I feel like I've tried everything.

**Comment by mookid8000** [comment]
I'm sorry, but you've missed a small part (which is VERY easy to miss):
```csharp
app.ApplicationServices.UseRebus();
```
which is still necessary with Rebus.ServiceProvider versions below 8*. 

So you're running with a fully constructed and fully operational Rebus instance, it's just running with 0 workers (i.e. it will not receive any messages). 

----
*) Rebus.ServiceProvider v8 will use the `IBackgroundService` mechanism to start/stop the bus at the right times, so from then on it will be easier to get things right. 🙂

**Comment by froens** [comment]
OOoooooh!

I really felt that there was just one line missing somewhere. I couldn't find it anywhere in the documentation: https://github.com/rebus-org/Rebus.ServiceProvider

I'm guessing the documentation is updated for 8* (which also explains why I couldn't get onCreated to work).

It works now.

Thanks a lot :-D

**Comment by mookid8000** [comment]
Oh yes, I hadn't even thought about that... but yes, the README reflects v8, so maybe you should simply go and
```psh
update-package rebus.serviceprovider -pre
```
?

It's pretty convenient with the `onCreated` callback, and it also has the ability to register multiple bus instances in the container, if you should ever want to do that.

**Comment by froens** [comment]
Yeah - I'm going to go for 8*

Thanks a lot for the answers :-) (and also for an awesome framework).
