### ISSUE TITLE
AppInsights - diagnostic-id missing

### ISSUE THREAD

**Issue by Qball1337** [rebus-org/Rebus.AzureServiceBus#96]
AppInsights supports distributed logging out of the box. It uses a hook when a message is send to place a diagnostic-id header. At the receiving side it will auto fill in the current activity context based on this guid. 

We switched from a custom service bus implementation to Rebus and noticed that our distributed logging is gone. Everything is still logged but not grouped by operatingId/parentId. The diagnostic-id is gone from our messages.

Does Rebus support this feature? Or do we have to manually set a tracking header?

**Comment by Qball1337** [comment]
Header is now correctly set on the outgoing messages. Problem we see now: Activity.current is null when processing a message. All logs/exceptions that happen have no operation_id / parent_id

**Comment by mookid8000** [comment]
You might want to read [the wiki page about extending both the incoming and outgoing message pipelines](https://github.com/rebus-org/Rebus/wiki/Auto-flowing-user-context-extensibility-example) to see how one can fairly easily extend Rebus to automatically flow activity information like you want it to.

Please let me know if you need any more guidance. 🙂
